//HintName: UnionAttribute.g.cs
// <auto-generated by UnionSourceGen />
#nullable enable
namespace UnionGen {

    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class UnionAttribute<T1, T2> : Attribute {}
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class UnionAttribute<T1, T2, T3> : Attribute {}
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class UnionAttribute<T1, T2, T3, T4> : Attribute {}
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class UnionAttribute<T1, T2, T3, T4, T5> : Attribute {}
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class UnionAttribute<T1, T2, T3, T4, T5, T6> : Attribute {}

}