name: Build & Publish NuGet

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      PROJ_DIR: ${{github.workspace}}/UnionGen
      NUGET_DIR: ${{github.workspace}}/nupkgs

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Create Package Directory
        run: mkdir nupkgs
      - name: Pack
        run: dotnet pack -c ${{env.BUILD_CONFIG}} --include-symbols --output ${{env.NUGET_DIR}}
        working-directory: ${{env.PROJ_DIR}}
      - name: Publish
        working-directory: ${{env.NUGET_DIR}}
        run: dotnet nuget push *.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
      - name: Upload NuGet packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGet Packages
          path: ${{env.NUGET_DIR}}/*.nupkg
          retention-days: 1